# Generated by Django 5.2.12 on 2026-04-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('studies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='users.physicianprofile'),
        ),
        migrations.AddField(
            model_name='study',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies_assigned', to='users.physicianprofile'),
        ),
        migrations.AddField(
            model_name='study',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='study',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies_created', to='users.technicianprofile'),
        ),
        migrations.AddField(
            model_name='report',
            name='study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='studies.study'),
        ),
    ]
